### ISSUE TITLE
What is coldstart.class used for?

### ISSUE THREAD

**Issue by Arpaaaa** [zzt93/syncer#29]
hey, I've been reading your project code recently, it's awesome work and I don't know the usage of cold start, so cloud you please explain it? It would be very helpful for me， Thanks

**Comment by zzt93** [comment]
For example, you want sync a table in MySQL to ES for search. For two reasons, we need cold-start:
- First, in production env, the binlog of MySQL always has expire settings, which means you don't have all writes/updates to sync.
- Second, a table with 10 rows may have tens of GB binlog, which is not fast to sync

**Comment by Arpaaaa** [comment]
I got it, thanks!

**Comment by hy0619** [comment]
why are LocalProducerSink#output(SyncData data) need put data to hold queue  ,also put the same data to toFilter queue(in LocalConsumerSource.class) ? when coldstart finnish , the data in hold queue is always handle to toFilter queue ,So isn't this data being processed repeatedly?

![Image](https://github.com/user-attachments/assets/21ba7c06-fce5-4471-a37e-efd365ea9d56)
